// projects/dacia-over-reacts/src/components/About.tsx
import React from 'react'
import Wysiwyg from './wysiwyg'
import content from '../json/static.en-us.json'

export default function About() {
	return (
		<div className="ui grid">
			<div className="two wide column">
				<div className="block">
					<h1>{content.about.title}</h1>
				</div>
			</div>
			<div className="fourteen wide column">
				<Wysiwyg />
			</div>
		</div>
	)
}

// projects/vue/src/routes/about.vue
<template>
	<div class="ui grid">
		<div class="two wide column">
			<div class="block">
				<h1>{{content.about.title}}</h1>
			</div>
		</div>
		<div class="fourteen wide column">
			<wysiwyg></wysiwyg>
		</div>
	</div>
</template>

<script>

	import Wysiwyg from '../components/wysiwyg.vue'

	export default {
		components: {
			Wysiwyg
		},
		data: function () {
			return {
				content: require('../json/static.en-us.json')
			}
		}
	}

</script>
