// projects/dacia-over-reacts/src/pages/Resume.tsx
import Ad from '../components/ad-work'
import Education from '../components/education'
import Experience from '../components/experience'
import Objective from '../components/objective'
import Skills from '../components/skills'
import content from '../json/static.en-us.json'

export default function Resume() {
	return (
		<div>
			<div className="two wide column">
				<div className="block">
					<h1>{content.resume.title}</h1>
				</div>
			</div>

			<div className="fourteen wide column">
				<Ad />

				<address>{content.resume.address}</address>

				<p>
					<a
						href={content.resume.resumeUrl}
						target="_blank"
						rel="noopener noreferrer"
					>
						<i className="inverted file pdf outline icon" />
						{content.resume.resumeTitle}
					</a>
				</p>

				<h2 className="ui horizontal divider header">
					<i className="keyboard icon" />
					{content.resume.skills.title}
				</h2>

				<div className="ui attached segment">
					<Skills />
				</div>

				<h2 className="ui horizontal divider header">
					<i className="id badge icon" />
					{content.resume.objective.title}
				</h2>

				<div className="ui attached segment">
					<Objective />
				</div>

				<h2 className="ui horizontal divider header">
					<i className="desktop icon" />
					{content.resume.experiences.title}
				</h2>

				<div className="ui attached segment">
					<Experience />
				</div>

				<h2 className="ui horizontal divider header">
					<i className="university icon" />
					{content.resume.education.title}
				</h2>

				<div className="ui attached segment">
					<Education />
				</div>
			</div>
		</div>
	)
}

// projects/vue/src/routes/resume.vue
<template>
	<div class="ui grid">
		<div class="two wide column">
			<div class="block">
				<h1>{{content.resume.title}}</h1>
			</div>
		</div>
		<div class="fourteen wide column">
			<ad-work></ad-work>
			<address>{{content.resume.address}}</address>
			<p>
				<a :href="content.resume.resumeUrl" target="_blank">
					<i class="inverted file pdf outline icon"></i>
					{{content.resume.resumeTitle}}
				</a>
			</p>

			<h2 class="ui horizontal divider header">
				<i class="keyboard icon"></i>
				{{content.resume.skills.title}}
			</h2>
			<div class="ui attached segment">
				<skills></skills>
			</div>

			<h2 class="ui horizontal divider header">
				<i class="id badge icon"></i>
				{{content.resume.objective.title}}
			</h2>
			<div class="ui attached segment">
				<objective></objective>
			</div>

			<h2 class="ui horizontal divider header">
				<i class="desktop icon"></i>
				{{content.resume.experiences.title}}
			</h2>
			<div class="ui attached segment">
				<experience></experience>
			</div>

			<h2 class="ui horizontal divider header">
				<i class="university icon"></i>
				{{content.resume.education.title}}
			</h2>

			<div class="ui attached segment">
				<education></education>
			</div>
		</div>
	</div>
</template>

<script>

	import AdWork from '../components/ad-work.vue'
	import Skills from '../components/skills.vue'
	import Links from '../components/links.vue'
	import Objective from '../components/objective.vue'
	import Experience from '../components/experience.vue'
	import Education from '../components/education.vue'

	export default {
		components: {
			AdWork,
			Skills,
			Links,
			Objective,
			Experience,
			Education
		},
		data: function () {
			return {
				content: require('../json/static.en-us.json')
			}
		}
	}

</script>

<style scoped lang="sass">

	h1
		left: -86px
		top: 145px

	address ~ p
		a
			color: $text

			&:hover,
			&.active
				color: $anchor-text-hover

</style>
