// projects/vue/src/routes/portfolio.vue
<template>
	<div class="ui grid">
		<div class="two wide column">
			<div class="block">
				<h1>{{content.portfolio.title}}</h1>
			</div>
		</div>
		<div class="fourteen wide column">
			<ad-work></ad-work>
			<p v-html="content.portfolio.copy"></p>

			<h2>{{content.portfolio.subtitle2}}</h2>
			<project-stats></project-stats>

			<h2>{{content.portfolio.subtitle3}}</h2>
			<project-timeline :projects="content.portfolio.projects"></project-timeline>
			
		</div>
	</div>
</template>

<script>

	import AdWork from '../components/ad-work.vue'
	import ProjectStats from '../components/project-stats.vue'
	import ProjectTimeline from '../components/project-timeline.vue'

	export default {
		components: {
			AdWork,
			ProjectStats,
			ProjectTimeline
		},
		data: function () {
			return {
				content: require('../json/static.en-us.json'),
				tag: undefined
			}
		}
	}

</script>

<style lang="sass" scoped>

	@import '../styles/main.sass'

	p:first-of-type
		max-width: 900px

	h1
		left: -98px
		top: 145px

</style>

// projects/dacia-over-reacts/src/pages/Portfolio.tsx
import AdWork from '../components/ad-work'
import ProjectStats from '../components/stats'
import ProjectTimeline from '../components/timeline'
import content from '../media/json/static.en-us.json'

export default function Portfolio() {
	return (
		<div className="portfolio ui grid">
			<div className="two wide column">
				<div className="block">
					<h1>{content.portfolio.title}</h1>
				</div>
			</div>

			<div className="fourteen wide column">
				<AdWork />

				<p dangerouslySetInnerHTML={{ __html: content.portfolio.copy }} />

				<div className="ui grid">
					<div className="two wide column">
						<h2>{content.portfolio.subtitle2}</h2>
						<ProjectStats />
					</div>

					<div
						className="fourteen wide column" id="timeline"
					>
						<h2>{content.portfolio.subtitle3}</h2>
						<ProjectTimeline />
					</div>
				</div>
			</div>
		</div>
	)
}
