// projects/dacia-over-reacts/src/components/experience.tsx
import React from 'react'
import content from '../json/static.en-us.json'

export default function Experience() {
	return (
		<div className="ui accordion">
			{content.resume.experiences.job.map((job, index) =>
				<span key={index}>
					<div className="title">
						<div className="ui icon message">
							<i className="laptop icon"></i>
							<div className="content">
								<div className="header">{job.title}</div>
							</div>
						</div>
					</div>
					<div className="content">
						<div className="ui feed">
							<div className="event">
								<div className="content">
									<div className="summary">
										<strong>{job.company}</strong>,
										{job.location},
										<span className="date">{job.date}</span>
									</div>

									<div className="extra text">
										{job.points.map((point, index) =>
											<div className="ui middle aligned divided list" key={index}>
												<div className="item">
													<i className="tiny circle icon"></i>
													<div className="content" dangerouslySetInnerHTML={{ __html: point }}></div>
												</div>
											</div>
										)}
									</div>
								</div>
							</div>
						</div>
					</div>
				</span>
			)}
		</div>
	)
}

// projects/vue/src/components/experience.vue
<template>
	<div class="ui accordion">
		<span v-for="job in content.resume.experiences.job" :key="job.id">
			<div class="title">
				<div class="ui icon message">
					<i class="laptop icon"></i>
					<div class="content">
						<div class="header">{{job.title}}</div>
					</div>
				</div>
			</div>
			<div class="content">
				<div class="ui feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								<strong>{{job.company}}</strong>,
								{{job.location}},
								<span class="date">{{job.date}}</span>
							</div>
							<div class="extra text">
								<div class="ui middle aligned divided list" v-for="point in job.points" :key="point.id">
									<div class="item">
										<i class="tiny circle icon"></i>
										<div class="content" v-html="point"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</span>
	</div>
</template>

<script>

	export default {
		data: function () {
			return {
				content: require('../json/static.en-us.json')
			}
		},
		mounted() {
			$('.ui.accordion').accordion()
		}
	}

</script>

<style scoped lang="sass">

	.ui.message
		padding-bottom: 0
		padding-top: 0

		.header:not(.ui)
			margin-bottom: 0

	.ui.card
		.content
			padding-top: 0

</style>
