// projects/dacia-over-reacts/src/components/skills.tsx
import React from 'react'
import content from '../json/static.en-us.json'

export default function Skills() {
	return (
		<table className="ui definition table">
			<tbody>
				{content.resume.skills.categories.map((skill, index) =>
					<tr key={index}>
						<td className="two wide column">{skill.title}</td>
						<td>{skill.copy}</td>
					</tr>
				)}
			</tbody>
		</table>
	)
}

// projects/vue/src/components/skills.vue
<template>
	<table class="ui definition table">
		<tbody>
			<tr v-for="skill in content.resume.skills.categories" :key="skill.id">
				<td class="two wide column">{{skill.title}}</td>
				<td>{{skill.copy}}</td>
			</tr>
		</tbody>
	</table>
</template>

<script>

	export default {
		data: function () {
			return {
				content: require('../json/static.en-us.json')
			}
		}
	}

</script>
