// projects/vue/src/components/ad-work.vue
<template>
	<div class="ui icon ad message">
		<i class="laptop icon"></i>
		<div class="content">
			<div class="header">{{ content.common.ad.work.title }}</div>
			<p>{{ content.common.ad.work.copy }}</p>
		</div>
	</div>
</template>

<script>

export default {
	data() {
		return {
			content: require('../json/static.en-us.json'),
		}
	},
}

</script>

// projects/dacia-over-reacts/src/components/ad-work.tsx
import React from 'react'
import content from '../json/static.en-us.json'

export default function AdWork() {
	return (
		<div className="ui icon ad message">
			<i className="laptop icon"></i>
			<div className="content">
				<div className="header">{content.common.ad.work.title}</div>
				<p>{content.common.ad.work.copy}</p>
			</div>
		</div>
	)
}
