// projects/vue/src/components/links.vue
<template>
	<div class="ui card">
		<div class="ui horizontal list">
			<div class="item" v-for="link in content.resume.links.categories" :key="link.id">
				<div class="content">
					<a :href="link.url" self="_blank">{{link.title}}</a>
				</div>
			</div>
		</div>
	</div>
</template>

<script>

	export default {
		data: function () {
			return {
				content: require('../json/static.en-us.json')
			}
		}
	}

</script>

// projects/dacia-over-reacts/src/components/links.tsx
import content from '../media/json/static.en-us.json'

export default function Links() {
	return (
		<div className="ui card">
			<div className="ui horizontal list">
				{content.resume.links.categories.map((link, index) =>
					<div className="item" key={index}>
						<div className="content">
							<a href={link.url} target="_blank">{link.title}</a>
						</div>
					</div>
				)}
			</div>
		</div>
	)
}
