// projects/vue/src/components/objective.vue
<template>
	<div class="ui card">
		<div class="content">
			<div class="description">
				<p>{{content.resume.objective.copy}}</p>
			</div>
		</div>
	</div>
</template>

<script>

export default {
	data() {
		return {
			content: require('../json/static.en-us.json'),
		}
	},
}

</script>

<style scoped lang="sass">

	.ui.card
		.content
			padding-top: 0

</style>

// projects/dacia-over-reacts/src/components/objective.tsx
import content from '../media/json/static.en-us.json'

export default function Objective() {
	return (
		<div className="objective ui card">
			<div className="content">
				<div className="description">
					<p>{content.resume.objective?.copy ?? 'Objective not available'}</p>
				</div>
			</div>
		</div>
	)
}
